---
name: refBun
main: ref\bundle\refBun
version: 3.1.1
api: [4.0.0]
author: 'refTeam'
description: '[tool] Several tools to help with pmmp plugin development'
load: STARTUP
loadbefore: ['DevTools']

commands:
  refbundle:
    description: Build plugin with more option
    usage: /refbundle <plugin name | *>
    aliases: [build, refbun, rb, bb]
    permission: refbundle.cmd

permissions:
  refbundle.cmd:
    description: 'Build plugin'
    default: op
...
